class Authority < ActiveRecord::Base
  attr_accessible :authoritable_id, :authoritable_type
  
  belongs_to :authoritable, :polymorphic => true
  
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: authorities
#
# * id                :integer         not null
#   authoritable_id   :integer
#   authoritable_type :string(255)
#   created_at        :datetime        not null
#   updated_at        :datetime        not null
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
