class Comment < ActiveRecord::Base
  attr_accessible :commentable_id, :commentable_type, :name
  
  belongs_to :commentable, :polymorphic => true
  
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: comments
#
# * id               :integer         not null
#   name             :string(255)
#   commentable_id   :integer
#   commentable_type :string(255)
#   created_at       :datetime        not null
#   updated_at       :datetime        not null
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
