class Domain < ActiveRecord::Base
  attr_accessible :code, :name
  
  has_many :contexts
  has_many :translations, :through => :contexts
  
  belongs_to :document
  acts_as_tree :order => "name"
  
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: domains
#
# * id          :integer         not null
#   name        :string(255)
#   code        :string(255)
#   created_at  :datetime        not null
#   updated_at  :datetime        not null
#   document_id :integer
#   parent_id   :integer
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
