class Group < ActiveRecord::Base
  attr_accessible :type, :name
  
  has_many :memberships
  has_many :users, :through => :memberships
  
  has_many :authorities, :as => :authoritable
  
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: groups
#
# * id         :integer         not null
#   group_type :string(255)
#   created_at :datetime        not null
#   updated_at :datetime        not null
#   name       :string(255)
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
