class Language < ActiveRecord::Base
  attr_accessible :iso_code, :name
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: languages
#
# * id         :integer         not null
#   name       :string(255)
#   iso_code   :string(255)
#   created_at :datetime        not null
#   updated_at :datetime        not null
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
