class Location < ActiveRecord::Base
  attr_accessible :locality, :country, :latitude, :longitude
  
  geocoded_by :locality
   
  
  
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: locations
#
# * id         :integer         not null
#   locality   :string(255)
#   country    :string(255)
#   latitude   :float
#   longitude  :float
#   created_at :datetime        not null
#   updated_at :datetime        not null
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
