class Membership < ActiveRecord::Base
  attr_accessible :created_on, :expired, :expires_on, :group_id, :user_id
  
  belongs_to :user
  belongs_to :group
  
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: memberships
#
# * id         :integer         not null
#   user_id    :integer
#   group_id   :integer
#   created_on :datetime
#   expires_on :datetime
#   expired    :boolean
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
