class Rating < ActiveRecord::Base
  attr_accessible :ratable_id, :ratable_type, :score
  
  belongs_to :ratable, :polymorphic => true
  
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: ratings
#
# * id           :integer         not null
#   score        :integer
#   ratable_id   :integer
#   ratable_type :string(255)
#   created_at   :datetime        not null
#   updated_at   :datetime        not null
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
