class RegEx < ActiveRecord::Base
  attr_accessible :id, :language_id, :regex_category, :expression
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: reg_exes
#
# * id             :integer         not null
#   language_id    :integer
#   regex_category :string(255)
#   expression     :text
#
#  Indexes:
#   index_reg_exes_on_expression  expression
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
