class User < ActiveRecord::Base
  attr_accessible :name, :subscribed
  
  
  #predefined queries
  scope :by_name, order(:name)
  scope :subscribed, where(:subscribed => true) 
  
  
  has_many :memberships
  has_many :groups, :through => :memberships
  
  has_many :former_groups, :through => :memberships, :source => :group, :conditions => [:expired => true]
  
  
  has_many :authorities, :as => :authoritable
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: users
#
# * id         :integer         not null
#   name       :string(255)
#   subscribed :boolean
#   created_at :datetime        not null
#   updated_at :datetime        not null
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
